[package]
name = "godot-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "2d", "3d"] # possibly: "ffi"
categories = ["game-engines", "graphics"]

[features]
default = []
trace = []
codegen-fmt = ["godot-ffi/codegen-fmt"]
codegen-full = ["godot-codegen/codegen-full"]
double-precision = ["godot-codegen/double-precision"]
custom-godot = ["godot-ffi/custom-godot", "godot-codegen/custom-godot"]

[dependencies]
godot-ffi = { path = "../godot-ffi" }

# See https://docs.rs/glam/latest/glam/index.html#feature-gates
glam = { version = "0.22", features = ["debug-glam-assert"] }

# Reverse dev dependencies so doctests can use `godot::` prefix
[dev-dependencies]
godot = { path = "../godot" }

[build-dependencies]
godot-codegen = { path = "../godot-codegen" }
